"""add_cart_module

Revision ID: 209787ecea66
Revises: 7871a028a220
Create Date: 2025-12-17 15:15:25.716707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '209787ecea66'
down_revision: Union[str, Sequence[str], None] = '7871a028a220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='关联用户ID'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='关联商品ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='购买数量'),
    sa.Column('selected', sa.Boolean(), nullable=True, comment='是否选中 (结算用)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cart_user_product', 'cart_items', ['user_id', 'product_id'], unique=True)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='分类名称',
               existing_nullable=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序权重，数值越大越靠前',
               existing_comment='排序权重，越大越前',
               existing_nullable=True)
    op.alter_column('categories', 'is_visible',
               existing_type=sa.BOOLEAN(),
               comment='是否可见 (软删除或隐藏)',
               existing_nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.BIGINT(),
               comment='关联订单ID',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.BIGINT(),
               comment='关联商品ID (商品删除后可能为空，但快照保留)',
               existing_nullable=True)
    op.alter_column('order_items', 'product_name',
               existing_type=sa.VARCHAR(length=100),
               comment='下单时的商品名称快照',
               existing_nullable=False)
    op.alter_column('order_items', 'product_image',
               existing_type=sa.VARCHAR(length=255),
               comment='下单时的商品图片快照',
               existing_nullable=True)
    op.alter_column('order_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='下单时的商品单价快照',
               existing_comment='购买时的单价',
               existing_nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment='购买数量',
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.BIGINT(),
               comment='下单用户ID',
               existing_nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='商品总价 (未含运费)',
               existing_comment='商品总价',
               existing_nullable=False)
    op.alter_column('orders', 'final_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='实付总金额',
               existing_comment='实付金额',
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.INTEGER(),
               comment='订单状态',
               existing_nullable=False)
    op.alter_column('orders', 'delivery_type',
               existing_type=sa.VARCHAR(length=20),
               comment='配送方式枚举: delivery(配送) / pickup(自提)',
               existing_comment='枚举: delivery / pickup',
               existing_nullable=False)
    op.alter_column('orders', 'address_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='收货地址快照',
               existing_nullable=True)
    op.alter_column('orders', 'pickup_code',
               existing_type=sa.VARCHAR(length=10),
               comment='6位自提核销码 (仅自提单有效)',
               existing_comment='6位核销码',
               existing_nullable=True)
    op.alter_column('orders', 'pickup_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='用户预约的自提时间',
               existing_comment='预约自提时间',
               existing_nullable=True)
    op.alter_column('orders', 'transaction_id',
               existing_type=sa.VARCHAR(length=64),
               comment='微信支付流水号 (支付回调写入)',
               existing_comment='微信支付流水号',
               existing_nullable=True)
    op.alter_column('orders', 'remark',
               existing_type=sa.VARCHAR(length=255),
               comment='用户订单备注',
               existing_comment='用户备注',
               existing_nullable=True)
    op.alter_column('orders', 'reject_reason',
               existing_type=sa.VARCHAR(length=255),
               comment='商家拒单原因 (仅拒单时有值)',
               existing_comment='商家拒单原因',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='下单时间',
               existing_nullable=True)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               comment='关联分类ID',
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='商品名称',
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment='商品详情描述',
               existing_nullable=True)
    op.alter_column('products', 'thumb_url',
               existing_type=sa.VARCHAR(length=255),
               comment='商品缩略图URL',
               existing_comment='商品缩略图',
               existing_nullable=True)
    op.alter_column('products', 'original_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='原价/划线价 (展示用)',
               existing_comment='原价/划线价',
               existing_nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               comment='库存数量',
               existing_comment='库存',
               existing_nullable=False)
    op.alter_column('products', 'sales_count',
               existing_type=sa.INTEGER(),
               comment='累计销量 (展示用)',
               existing_comment='销量(展示用)',
               existing_nullable=True)
    op.alter_column('products', 'status',
               existing_type=sa.INTEGER(),
               comment='状态: 1=上架, 0=下架',
               existing_comment='1:上架 0:下架',
               existing_nullable=True)
    op.alter_column('products', 'specs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='预留字段：多规格信息 (JSON格式)',
               existing_comment='预留字段：多规格信息',
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('shop_config', 'store_name',
               existing_type=sa.VARCHAR(length=100),
               comment='店铺名称',
               existing_nullable=False)
    op.alter_column('shop_config', 'store_address',
               existing_type=sa.VARCHAR(length=255),
               comment='店铺物理地址 (自提点)',
               existing_nullable=True)
    op.alter_column('shop_config', 'store_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='店铺联系电话',
               existing_nullable=True)
    op.alter_column('shop_config', 'is_open',
               existing_type=sa.BOOLEAN(),
               comment='总开关: true=营业中, false=打烊',
               existing_comment='总开关: true营业 false打烊',
               existing_nullable=True)
    op.alter_column('shop_config', 'open_time',
               existing_type=postgresql.TIME(),
               comment='每日营业开始时间',
               existing_nullable=False)
    op.alter_column('shop_config', 'close_time',
               existing_type=postgresql.TIME(),
               comment='每日营业结束时间',
               existing_nullable=False)
    op.alter_column('shop_config', 'min_order_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='起送金额 (低于此金额不可下单)',
               existing_comment='起送金额',
               existing_nullable=True)
    op.alter_column('shop_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后修改时间',
               existing_nullable=True)
    op.alter_column('user_addresses', 'user_id',
               existing_type=sa.BIGINT(),
               comment='关联用户ID',
               existing_nullable=False)
    op.alter_column('user_addresses', 'contact_name',
               existing_type=sa.VARCHAR(length=64),
               comment='联系人姓名',
               existing_nullable=False)
    op.alter_column('user_addresses', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='联系人电话',
               existing_nullable=False)
    op.alter_column('user_addresses', 'detail_address',
               existing_type=sa.VARCHAR(length=255),
               comment='详细地址 (如: xx路xx小区x号)',
               existing_nullable=False)
    op.alter_column('user_addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='是否为默认地址',
               existing_nullable=True)
    op.alter_column('user_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('users', 'openid',
               existing_type=sa.VARCHAR(length=64),
               comment='微信OpenID (小程序登录用)',
               existing_comment='微信OpenID',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=64),
               comment='用户昵称',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=255),
               comment='用户头像URL',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='注册时间',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='注册时间',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='用户头像URL',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='用户昵称',
               existing_nullable=True)
    op.alter_column('users', 'openid',
               existing_type=sa.VARCHAR(length=64),
               comment='微信OpenID',
               existing_comment='微信OpenID (小程序登录用)',
               existing_nullable=True)
    op.alter_column('user_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('user_addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为默认地址',
               existing_nullable=True)
    op.alter_column('user_addresses', 'detail_address',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='详细地址 (如: xx路xx小区x号)',
               existing_nullable=False)
    op.alter_column('user_addresses', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='联系人电话',
               existing_nullable=False)
    op.alter_column('user_addresses', 'contact_name',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='联系人姓名',
               existing_nullable=False)
    op.alter_column('user_addresses', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='关联用户ID',
               existing_nullable=False)
    op.alter_column('shop_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后修改时间',
               existing_nullable=True)
    op.alter_column('shop_config', 'min_order_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='起送金额',
               existing_comment='起送金额 (低于此金额不可下单)',
               existing_nullable=True)
    op.alter_column('shop_config', 'close_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='每日营业结束时间',
               existing_nullable=False)
    op.alter_column('shop_config', 'open_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='每日营业开始时间',
               existing_nullable=False)
    op.alter_column('shop_config', 'is_open',
               existing_type=sa.BOOLEAN(),
               comment='总开关: true营业 false打烊',
               existing_comment='总开关: true=营业中, false=打烊',
               existing_nullable=True)
    op.alter_column('shop_config', 'store_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='店铺联系电话',
               existing_nullable=True)
    op.alter_column('shop_config', 'store_address',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='店铺物理地址 (自提点)',
               existing_nullable=True)
    op.alter_column('shop_config', 'store_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='店铺名称',
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('products', 'specs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='预留字段：多规格信息',
               existing_comment='预留字段：多规格信息 (JSON格式)',
               existing_nullable=True)
    op.alter_column('products', 'status',
               existing_type=sa.INTEGER(),
               comment='1:上架 0:下架',
               existing_comment='状态: 1=上架, 0=下架',
               existing_nullable=True)
    op.alter_column('products', 'sales_count',
               existing_type=sa.INTEGER(),
               comment='销量(展示用)',
               existing_comment='累计销量 (展示用)',
               existing_nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               comment='库存',
               existing_comment='库存数量',
               existing_nullable=False)
    op.alter_column('products', 'original_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='原价/划线价',
               existing_comment='原价/划线价 (展示用)',
               existing_nullable=True)
    op.alter_column('products', 'thumb_url',
               existing_type=sa.VARCHAR(length=255),
               comment='商品缩略图',
               existing_comment='商品缩略图URL',
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='商品详情描述',
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='商品名称',
               existing_nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联分类ID',
               existing_nullable=True)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='下单时间',
               existing_nullable=True)
    op.alter_column('orders', 'reject_reason',
               existing_type=sa.VARCHAR(length=255),
               comment='商家拒单原因',
               existing_comment='商家拒单原因 (仅拒单时有值)',
               existing_nullable=True)
    op.alter_column('orders', 'remark',
               existing_type=sa.VARCHAR(length=255),
               comment='用户备注',
               existing_comment='用户订单备注',
               existing_nullable=True)
    op.alter_column('orders', 'transaction_id',
               existing_type=sa.VARCHAR(length=64),
               comment='微信支付流水号',
               existing_comment='微信支付流水号 (支付回调写入)',
               existing_nullable=True)
    op.alter_column('orders', 'pickup_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='预约自提时间',
               existing_comment='用户预约的自提时间',
               existing_nullable=True)
    op.alter_column('orders', 'pickup_code',
               existing_type=sa.VARCHAR(length=10),
               comment='6位核销码',
               existing_comment='6位自提核销码 (仅自提单有效)',
               existing_nullable=True)
    op.alter_column('orders', 'address_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='收货地址快照',
               existing_nullable=True)
    op.alter_column('orders', 'delivery_type',
               existing_type=sa.VARCHAR(length=20),
               comment='枚举: delivery / pickup',
               existing_comment='配送方式枚举: delivery(配送) / pickup(自提)',
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='订单状态',
               existing_nullable=False)
    op.alter_column('orders', 'final_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='实付金额',
               existing_comment='实付总金额',
               existing_nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='商品总价',
               existing_comment='商品总价 (未含运费)',
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='下单用户ID',
               existing_nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='购买数量',
               existing_nullable=False)
    op.alter_column('order_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='购买时的单价',
               existing_comment='下单时的商品单价快照',
               existing_nullable=False)
    op.alter_column('order_items', 'product_image',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='下单时的商品图片快照',
               existing_nullable=True)
    op.alter_column('order_items', 'product_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='下单时的商品名称快照',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='关联商品ID (商品删除后可能为空，但快照保留)',
               existing_nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='关联订单ID',
               existing_nullable=False)
    op.alter_column('categories', 'is_visible',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否可见 (软删除或隐藏)',
               existing_nullable=True)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序权重，越大越前',
               existing_comment='排序权重，数值越大越靠前',
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='分类名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index('idx_cart_user_product', table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
