"""add_is_removed_to_order_items

Revision ID: 379cb7e85eaf
Revises: 209787ecea66
Create Date: 2025-12-18 10:05:08.465421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379cb7e85eaf'
down_revision: Union[str, Sequence[str], None] = '209787ecea66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_removed', sa.Boolean(), nullable=True, comment='是否已被管理员移除'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_removed')
    # ### end Alembic commands ###
