"""update user model nullable openid and unique phone

Revision ID: 7871a028a220
Revises: 87481f5cd990
Create Date: 2025-12-17 11:39:45.787643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7871a028a220'
down_revision: Union[str, Sequence[str], None] = '87481f5cd990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'openid',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_comment='微信OpenID')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'openid',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='微信OpenID')
    # ### end Alembic commands ###
