"""init_tables

Revision ID: 87481f5cd990
Revises: 
Create Date: 2025-12-17 11:27:02.079558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87481f5cd990'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序权重，越大越前'),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('shop_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('store_address', sa.String(length=255), nullable=True),
    sa.Column('store_phone', sa.String(length=20), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True, comment='总开关: true营业 false打烊'),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='基础运费'),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='起送金额'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_config_id'), 'shop_config', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False, comment='微信OpenID'),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='业务订单号，如 20231217xxxx'),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='商品总价'),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='运费'),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='实付金额'),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('delivery_type', sa.String(length=20), nullable=False, comment='枚举: delivery / pickup'),
    sa.Column('address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pickup_code', sa.String(length=10), nullable=True, comment='6位核销码'),
    sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=True, comment='预约自提时间'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='核销/完成时间'),
    sa.Column('transaction_id', sa.String(length=64), nullable=True, comment='微信支付流水号'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='用户备注'),
    sa.Column('reject_reason', sa.String(length=255), nullable=True, comment='商家拒单原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('idx_orders_pickup_code', 'orders', ['pickup_code'], unique=False)
    op.create_index('idx_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumb_url', sa.String(length=255), nullable=True, comment='商品缩略图'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='当前售价'),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='原价/划线价'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='库存'),
    sa.Column('sales_count', sa.Integer(), nullable=True, comment='销量(展示用)'),
    sa.Column('status', sa.Integer(), nullable=True, comment='1:上架 0:下架'),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='预留字段：多规格信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_cat_status', 'products', ['category_id', 'status'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('detail_address', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_id'), 'user_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_image', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='购买时的单价'),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('idx_products_cat_status', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('idx_orders_user_status', table_name='orders')
    op.drop_index('idx_orders_pickup_code', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shop_config_id'), table_name='shop_config')
    op.drop_table('shop_config')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
